import express from "express";
import Category from "../models/Category.js";
import { deleteItem, getById } from "./generic.js";

const router = express.Router();

// GET ALL
router.get("/", async (req, res) => {
  try {
    const categories = await Category.find().sort({ createdAt: -1 });
    res.status(200).json(categories);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST ADD
router.post("/add", async (req, res) => {
  try {
    // The slug is automatically generated by the pre-validate hook in the model
    const newCat = new Category(req.body);
    await newCat.save();
    res.status(201).json(newCat);
  } catch (err) {
    console.error("Add Category Error:", err.message);
    res.status(400).json({ 
      message: err.code === 11000 ? "Category name or slug already exists" : err.message 
    });
  }
});

// GET BY ID
router.get("/:id", (req, res) => getById(Category, req.params.id, res));

// DELETE
router.delete("/:id", (req, res) => deleteItem(Category, req.params.id, res));

// UPDATE
router.put("/:id", async (req, res) => {
  try {
    const updated = await Category.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true }
    );
    if (!updated) return res.status(404).json({ message: "Category not found" });
    res.status(200).json(updated);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

export default router;