export const productData = [
  {
    id: 1,
    brand: "ShilpoKotha",
    name: "Premium Cotton Panjabi",
    price: "2,450",
    rating: 5,
  },
  {
    id: 2,
    brand: "ShilpoKotha",
    name: "Heritage Silk Wear",
    price: "4,200",
    rating: 4,
  },
  {
    id: 3,
    brand: "ShilpoKotha",
    name: "Classic Dhakai Lungi",
    price: "1,150",
    rating: 5,
  },
  {
    id: 4,
    brand: "ShilpoKotha",
    name: "Embroidered Kurta",
    price: "3,100",
    rating: 4,
  },
  {
    id: 5,
    brand: "ShilpoKotha",
    name: "Cotton Casual Shirt",
    price: "1,850",
    rating: 5,
  },
  {
    id: 6,
    brand: "ShilpoKotha",
    name: "Formal Heritage Vest",
    price: "2,200",
    rating: 4,
  },
  {
    id: 7,
    brand: "ShilpoKotha",
    name: "Traditional Scarf",
    price: "850",
    rating: 5,
  },
  {
    id: 8,
    brand: "ShilpoKotha",
    name: "Hand-stitched Panjabi",
    price: "3,500",
    rating: 5,
  },
  {
    id: 9,
    brand: "ShilpoKotha",
    name: "Product Name 9",
    price: "000",
    rating: 5,
  },
  {
    id: 10,
    brand: "ShilpoKotha",
    name: "Product Name 10",
    price: "000",
    rating: 5,
  },
  {
    id: 11,
    brand: "ShilpoKotha",
    name: "Product Name 11",
    price: "000",
    rating: 5,
  },
  {
    id: 12,
    brand: "ShilpoKotha",
    name: "Product Name 12",
    price: "000",
    rating: 5,
  },
  {
    id: 13,
    brand: "ShilpoKotha",
    name: "Product Name 13",
    price: "000",
    rating: 5,
  },
  {
    id: 14,
    brand: "ShilpoKotha",
    name: "Product Name 14",
    price: "000",
    rating: 5,
  },
  {
    id: 15,
    brand: "ShilpoKotha",
    name: "Product Name 15",
    price: "000",
    rating: 5,
  },
  {
    id: 16,
    brand: "ShilpoKotha",
    name: "Product Name 16",
    price: "000",
    rating: 5,
  },
];
